[package]
name = "froghorn"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"

[dependencies]
minifb = "0.28"
openh264 = "0.8.0"
rodio = "0.20.1"
